// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGPf1IiaR1KhkinYG4EQzNKbBmUACu20k',
    appId: '1:458567752591:web:d630e411e9a8e5d0be09fa',
    messagingSenderId: '458567752591',
    projectId: 'livraison-8b627',
    authDomain: 'livraison-8b627.firebaseapp.com',
    storageBucket: 'livraison-8b627.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFslOLVMsBqALBiSGxLAXTu6lq9FDhMlM',
    appId: '1:458567752591:android:8a9e3cb336837c51be09fa',
    messagingSenderId: '458567752591',
    projectId: 'livraison-8b627',
    storageBucket: 'livraison-8b627.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB60AdOuH3U5FwhpruNgWW7CM5_uzwyYI',
    appId: '1:458567752591:ios:d7566c2e3721bdb0be09fa',
    messagingSenderId: '458567752591',
    projectId: 'livraison-8b627',
    storageBucket: 'livraison-8b627.appspot.com',
    iosClientId: '458567752591-oboconi0k3tl9t69joab9qo31hk1lqdt.apps.googleusercontent.com',
    iosBundleId: 'com.example.lastLivrai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB60AdOuH3U5FwhpruNgWW7CM5_uzwyYI',
    appId: '1:458567752591:ios:ef38d1fc2f3471b2be09fa',
    messagingSenderId: '458567752591',
    projectId: 'livraison-8b627',
    storageBucket: 'livraison-8b627.appspot.com',
    iosClientId: '458567752591-htdatr6e8ueu2nm8vtflbcvquep6onc0.apps.googleusercontent.com',
    iosBundleId: 'com.example.lastLivrai.RunnerTests',
  );
}
